version: 2
jobs: 
  build11: 
    docker:
      - image: maven:latest
    steps:
      - checkout
      - run: mkdir workspace
      - run: |
         cd  SpringMVCSecurityXML
         mvn  install
      
      - run: |
          mv   /root/project/SpringMVCSecurityXML/target/SpringMVCSecurityXML.war /root/project/workspace
          cd workspace
          ls
      - persist_to_workspace:  
           root: /root/project/workspace
           path: 
             - SpringMVCSecurityXML.war
  build2:
    docker:
      - image: tomcat:8-jre8
    steps:
      - attach_workspace:
                at: /usr/local/tomcat/webapps/ 
      - run: ls
workflows: 
  build_and_deploy:
     jobs:
      - build11
      - build2:
        requires:
           - build11
         


