version: 2
jobs:
  build11:

    docker:
         - image: maven:latest
    steps:

         - checkout
         - run: |
               pwd
               ls 
               mkdir /root/project/ahladh
               touch /root/project/ahladh/text
               echo "ahladh hi" > /root/project/ahladh/text
               cd ahladh
               ls
         - persist_to_workspace:
               root: ahladh
               paths: 
                  - text 
               
                
                              
  build22:

    docker:
         - image: tomcat:8-jre8
    steps: 
         - checkout
         - attach_workspace: 
             at: /root/project/ahladh
         - run: | 
             ls
            
          
                  
                
workflows: 
  version: 2
  build:
     jobs:
      - build11
      - build22: 
          requires: 
            - build11



