jobs:
  build11:

    docker:
         - image: maven:latest
    steps:

         - checkout
         - run: |
              
              
               mkdir  /root/project/ahladh
               mkdir /root/project/ahladh/chandu
               cd SpringMVCSecurityXML
                mvn  install
                cp  /root/project/SpringMVCSecurityXML/target/SpringMVCSecurityXML.war  /root/project/ahladh/chandu
               cd /root/project/ahladh
               ls
               hostname
         - run: hostname
         - persist_to_workspace:
               root: ahladh/chandu
               paths: 
                  - SpringMVCSecurityXML.war
                  
         - store_artifacts:
               path: /root/project/ahladh/chandu/SpringMVCSecurityXML.war
               
                
                              
  build22:


    docker:
         - image: tomcat:8-jre8
    steps: 
         - checkout
         - attach_workspace: 
             at: /root/project/ahladh/chandu
         - run: | 
             ls
             cp /root/project/ahladh/SpringMVCSecurityXML.war /usr/local/tomcat/webapps
             ls /usr/local/tomcat/webapps/
          
                  
                
workflows: 
  version: 2
  build:
     jobs:
      - build11
      - build22: 
          requires: 
            - build11
