version: 2
jobs: 
  build11: 
    working_directory: /root/project
    docker:
      - image: maven:latest
    steps:
      - checkout
      - run: mkdir workspace
      - run: |
         cd  SpringMVCSecurityXML
         mvn  install
      
      - run: |
          mv   /root/project/SpringMVCSecurityXML/target/SpringMVCSecurityXML.war /root/project/workspace
          cd workspace
          ls
      - persist_to_workspace:  
           root: workspace
           path: 
             - ./project/workspace/SpringMVCSecurityXML.war
             
             
workflows: 
  build_and_deploy:
     jobs:
      - build11
      


