version: 2
jobs: 
  build1: 
    docker:
      - image: maven:latest
    steps:
      - checkout
      - run: | 
         cd  SpringMVCSecurityXML
         mvn  install
      - persist_to_workspace:
           root: 
             - ./project/SpringMVCSecurityXML/target/
           path: 
             - SpringMVCSecurityXML.war
             
  build2:
    docker:
      - image: tomcat:8-jre8
    steps:
      - attach_workspace:
          at: /usr/local/tomcat/webapps 
