version: 2
jobs: 
  build: 
    docker:
      - image: maven:latest
    steps:
      - checkout
      - run: | 
         cd  SpringMVCSecurityXML
         mvn clean install
         cd target
       
         
         
