version: 2
jobs: 
  build11: 
    docker:
      - image: maven:latest
    steps:
      - checkout
      - run: mkdir workspace
      - run: |
         cd  SpringMVCSecurityXML
         mvn  install
      
      - run: |
          mv   /root/project/SpringMVCSecurityXML/target/SpringMVCSecurityXML.war /root/project/workspace
          cd workspace
          ls
      - persist_to_workspace:  
           root: workspace
           path: 
             - ./workspace/SpringMVCSecurityXML.war
             
            
workflows: 
  version: 2
  build_and_deploy:
     jobs:
      - build11

         


