version: 2
jobs: 
  build11: 
    working_directory: /tmp
    docker:
      - image: maven:latest
    steps:
      - checkout
      - run: mkdir workspace
      - run: |
         cd  SpringMVCSecurityXML
         mvn  install
      
      - run: |
          mv   /root/project/SpringMVCSecurityXML/target/SpringMVCSecurityXML.war /root/project/workspace
          cd workspace
          ls

         


